[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "WeaponUpgradeData.lua"
pattern = '''
ScreenData.WeaponUpgradeScreen =
{
	Components = {},
'''
position = "after"
payload = '''
	StartingIndex = 1,
	NumPerPage = 4,
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "WeaponUpgradeData.lua"
pattern = '''
		ActionBar =
		{
			X = UIData.ContextualButtonXRight,
			Y = UIData.ContextualButtonY,
			AutoAlignContextualButtons = true,
			AutoAlignJustification = "Right",

			ChildrenOrder =
			{
				"CloseButton",
				"SelectButton",
			},

			Children = 
			{
				SelectButton =
				{
					Graphic = "ContextualActionButton",
					
					Alpha = 0.0,
					Data =
					{
						-- Dummy button
					},
					Text = "Menu_ChangeAspect",
					TextArgs = UIData.ContextualButtonFormatRight,
				},
				
				CloseButton =
				{
					Graphic = "ContextualActionButton",
					Data =
					{
						OnMouseOverFunctionName = "MouseOverContextualAction",
						OnMouseOffFunctionName = "MouseOffContextualAction",
						OnPressedFunctionName = "CloseWeaponUpgradeScreen",
						ControlHotkeys = { "Cancel", },
					},
					Text = "Menu_Exit",
					TextArgs = UIData.ContextualButtonFormatRight,
				},
			},
		},
'''
position = "after"
payload = '''
		PageNumber =
		{
			Text = "BoonInfo_PageNumber",
			X = 600 + 350,
			Y = UIData.ContextualButtonY,
			TextArgs =
			{
				FontSize = 28,
				OffsetX = 0,
				OffsetY = 0,
				Font = "NumericP22UndergroundSCMedium",
				ShadowBlur = 0, ShadowColor = {0,0,0,1}, ShadowOffset={0, 2},
				LuaKey = "TempTextData",
				LuaValue = { CurrentPageNum = 0, NumPages = 0 },
				Justification = "Center",
				DataProperties =
				{
					OpacityWithOwner = true,
				},
			},
		},

		PageUp =
		{
			Graphic = "ButtonCodexUp",
			X = 520 + 350,
			Y = UIData.ContextualButtonY + 3,
			Alpha = 0.0,
			Data =
			{
				OnPressedFunctionName = "zerp_AspectExtender_WeaponUpgradeScreenPrevious",
				ControlHotkeys = {"MenuLeft"},
				MouseControlHotkeys = {"MenuUp"}
			},
			InteractProperties =
			{
				FreeFormSelectOffsetX = 0,
				FreeFormSelectOffsetY = -1000,
			},
		},

		PageDown =
		{
			Graphic = "ButtonCodexDown",
			X = 680 + 350,
			Y = UIData.ContextualButtonY - 3,
			Alpha = 0.0,
			Data =
			{
				OnPressedFunctionName = "zerp_AspectExtender_WeaponUpgradeScreenNext",
				ControlHotkeys = {"MenuRight"},
				MouseControlHotkeys = {"MenuDown"}
			},
			InteractProperties =
			{
				FreeFormSelectOffsetX = 0,
				FreeFormSelectOffsetY = 0,
			},
		},
'''
match_indent = false
times = 1